### PR TITLE
#161255319 Users should be able to create articles

### PR DESCRIPTION
**Pull request by AnguleMathias**
#### What does this PR do?
* Create New Article 
* Enables author to update his/her article.
* Enables author to delete his/her article.
* Enables User to fetch all articles.
* Enables User to fetch a single article.

##### Description of Task to be completed?
* Enables Logged in Users to use CRUD for articles.

#### How should this be manually tested?
* Clone the repo
* Checkout to branch: `ft-articles-161255319`
* Run `npm install` 
* Run `npm start`.

###### or
* Click here: [link to heroku review apps](https://ah-codeofduty-frontend-s-pr-19.herokuapp.com/)

#### What are the relevant pivotal tracker stories?
#161255319 - [Users should be able to create articles](https://www.pivotaltracker.com/story/show/161255319)

###### 1. Create Article
screenshot 2018-12-14 at 07 49 54

###### 2. View all articles
screenshot 2018-12-14 at 07 49 42

###### 3. View single article
screenshot 2018-12-14 at 07 51 01

###### 4. Delete article
screenshot 2018-12-14 at 07 51 30

### CODE REVIEW

**Review by KITHU — APPROVED** [review]
lgtm

**Review by maxwellgithinji — APPROVED** [review]
LGTM

**Review by njeri-ngigi — DISMISSED** [review]

**Comment by meshnesh** [comment]
screenshot 2018-12-16 at 19 05 26
The articles are to close to the navigation look into creating some space in between them, balance the spacing to match the left and the right or half the spacing.

**Comment by meshnesh** [comment]
screenshot 2018-12-16 at 19 09 57
Please a footer for the application as it lacks one

**Comment by meshnesh** [comment]
Also noticed that am not able to access the `/articles` unless am loggedIn, this is not good UX as the user should be able to view articles unless they are creating, updating or deleting it is when they should not be able to unless loggedIn.

**Comment by meshnesh** [comment]
screenshot 2018-12-16 at 19 13 37
There is a lot of white spaces on the right and bottom sides of the webpage, following good UI principles kindly look into balancing the content within the webpage, as well increase the height of the blog body as it is too small

**Comment by meshnesh** [comment]
screenshot 2018-12-16 at 19 17 05
The designs of the cards in the home page and the `/articles` do not match, kindly look into making them look the same and maintain a consistent look

**Comment by meshnesh** [comment]
screenshot 2018-12-16 at 19 20 04
kindly remove the` New Articles` tab from the navigation as the user is still not yet loggedIn or registered. Only show it once a  user is loggedIn to create and account.

**Review by njeri-ngigi — APPROVED** [review]

**Pull request merged**
