### PR TITLE
#161255317 Social Login

### PR DESCRIPTION
**Pull request by AnguleMathias**
#### What does this PR do?
* Add's social login to the application
* It also adds action types for a successful login.

#### Description of tasks to be completed?
* Users should be able to Login via social login to the application

#### How should this be manually tested?
* Run npm install to install all dependencies
* Run npm start
* Click on `login` button
* Click the social login buttons

#### What are the relevant pivotal tracker stories?
* #161255317 - [Users should be able to Login via Google Facebook or Twitter](https://www.pivotaltracker.com/story/show/161255317)

#### Screenshots
screenshot 2018-12-10 at 19 16 04

### CODE REVIEW

**Comment by meshnesh** [comment]
@AnguleMathias your P.R has code duplication issues stated in code climate https://codeclimate.com/github/andela/ah-codeofduty-frontend/pull/14, please fix this so that your P.R can be merged.

**Review by KITHU — APPROVED** [review]
looks good to me

**Review by njeri-ngigi — CHANGES_REQUESTED** [review]
You still have 4 counts of duplication...you can use one method for social auth and call it with different parameters

**Review by njeri-ngigi — APPROVED** [review]

**Review by maxwellgithinji — APPROVED** [review]
LGTM

**Pull request merged**
