### PR TITLE
#161255320 Users should be able to rate articles

### PR DESCRIPTION
**Pull request by 3N61N33R**
#### What does this PR do?
adds rating functionality
#### Description of task to be completed
A 5-star rating system is the end goal. 
Authenticated users get a visual feedback of the average rating of their articles

#### Relevant PT stories
[Users should be able to rate articles](https://www.pivotaltracker.com/story/show/161255320)

#### Screenshot
screen shot 2018-12-17 at 12 15 27

### CODE REVIEW

**Review by njeri-ngigi — APPROVED** [review]

**Comment by meshnesh** [comment]
@graycadeau kindly look into increasing the dropping -1.2%coverage stated by code climate

**Review by AnguleMathias — CHANGES_REQUESTED** [review]
Great work, check on dropping test coverage

**Review by AnguleMathias — APPROVED** [review]

**Review by maxwellgithinji — APPROVED** [review]
LGTM

**Review by KITHU — APPROVED** [review]
lgtm

**Pull request merged**
